### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by lexdene** [yetone/olo#90]
开了 warning 以后，key 会报个 warning:

    ~/olo/olo/key.py:7: DeprecationWarning: object.__init__() takes no parameters
      super(Key, self).__init__(*args, **kwargs)

**Comment by yetone** [comment]
现在豆瓣用的是哪个 olo 啊？

**Comment by lexdene** [comment]
有几个项目已经迁到 pypi 上的版本了。
